### ISSUE TITLE
Using More Than One Custom Field Duplicates The Output

### ISSUE THREAD

**Issue by matugm** [projectdiscovery/katana#1025]
### katana version:

v1.1.0

### Current Behavior:

Having defined the following test page:

```html
dsfsdfdsf
<title>Test Page</title>
<h2>testingaaaa</h2>

aaaaaa
<a href='/c1'>B</a>
lñsdfjlsdfsfkdj

<p>cat@animals.com</p>
```

And these custom fields:

```yaml
- name: email
  type: regex
  part: response
  regex:
    - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)

- name: h2
  type: regex
  group: 1
  regex:
    - <h2>(.*)</h2>

- name: title
  type: regex
  group: 1
  regex:
    -  <title>(.*)</title>
```

With this `katana` command:

```
katana -u http://localhost:8000/test.html -v -f email,h2,title
```

Produces duplicate output fields:

```
[INF] Started standard crawling for => http://localhost:8000/test.html
[email] cat@animals.com
[h2] testingaaaa
[title] Test Page
[h2] testingaaaa
[title] Test Page
[email] cat@animals.com
[email] cat@animals.com
[h2] testingaaaa
[title] Test Page
```

### Expected Behavior:

Don't produce more elements than really exists on the page. For example, the "title" only appears once in the page but katana is displaying it 3 times. If I only use one custom tag (for example just -d title) it works as expected, but when I supply multiple custom tags this bug appears.

Thanks for the great tool. Hopefully it can be fixed! :)
