### ISSUE TITLE
Support Helper Function Calls in Form Configuration

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/katana#1227]
```yaml
# $HOME/.config/katana/form-config.yaml
name: "{{rand_first_name()}} {{rand_last_name()}}"
email: "{{rand_email()}}"
phone: "{{rand_phone()}}"
address: "{{rand_address()}}"
cc: "{{rand_credit_card()}}"
password: "{{rand_password()}}"
```
