### ISSUE TITLE
JSON output improvement

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/katana#21]
Current output:

```yaml
{
  "url": "https://www.hackerone.com/events/app-security-testing",
  "source": "a"
}
```

Updated output:

```yaml
{
  "timestamp": "2022-08-22T04:46:23.405849+05:30"
  "endpoint": "https://www.hackerone.com/events/app-security-testing",  # endpoint is discovered url
  "source": "https://www.hackerone.com/events/"  # source is page url where the endpoint got discovered 
  "tag": "a", 
  "attribute": "href"
}
```
