### ISSUE TITLE
Custom field support with config file

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/katana#92]
### Please describe your feature request:
By default, katana supports multiple pre-defined fields to customize output and can be extended to allow users to write custom fields in the config  file named `field-config.yaml` located at `~/.config/katana/`

Example field config file:

```yaml
# custom fields

- name: email
  type: regex
  regex:
  - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)
  - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)
  - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)

- name: phone
  type: regex
  regex:
  - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)
  - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)
  - ([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)
```

- `regex` is supported to write a custom field
- `group` field is supported with regex like nuclei
- regex will be applied on crawled response (header + body)
- single or multiple regex can be used with a custom field
- `name` value will be used as field name to pass with cli option
- `name` field needs to be unique + pre-defined names are reserved.
- `name` field validation to accept only `aA-zZ-0-9_-`
- default example field config file will be created upon 1st run.

```console
./katana -u https://www.hackerone.com -f email,phone 

lol@gmail.com
test@pd.io
aax@test.com
test@evil.com
+1-32424234
+1 32424234
+91324324324
```

```console
./katana -u https://www.hackerone.com -f email,phone -v

[email] lol@gmail.com
[email] test@pd.io
[email] aax@test.com
[email] test@evil.com
[phone] +1-32424234
[phone] +1 32424234
[phone] +91324324324
```
